development:
  adapter: em_mysql2
  encoding:
  reconnect:
  database: netlab_development
  username: netlab
  password: n3tl4b
  host: localhost
  pool: 5

test:
  adapter: em_mysql2
  encoding:
  reconnect:
  database: netlab_test
  username: netlab
  password: n3tl4b
  host: localhost
  pool: 5

production:
  adapter: em_mysql2
  encoding:
  reconnect:
  database: netlab_production
  username: netlab
  password: n3tl4b
  host: localhost
  pool: 5
