defaults: &defaults
  adapter: em_mysql2
  encoding:
  reconnect:
  database: netlab_production
  username: netlab
  password: n3tl4b
  host: localhost
  pool: 5

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
